import java.awt.Color;

/**
 *
 * @author Study
 */
public class Server extends java.awt.Frame {

    /**
     * Creates new form Server
     */
    public Server() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        scrollPane1 = new java.awt.ScrollPane();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        scrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(scrollPane1, java.awt.BorderLayout.CENTER);

        tf1.setText("");
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        add(tf1, java.awt.BorderLayout.NORTH);
        tf2.setEditable(false);
        tf2.setBackground(new Color(0x4136B5));
        scrollPane1.add(tf2);
        pack();
    }// </editor-fold>                        

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {                          
        System.exit(0);
    }                         

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {                                    
            // TODO add your handling code here:
    		
    		tf2.setText(tf2.getText()+"\n" + tf1.getText());
    		tf1.setText("");
    }                                   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	Server server = new Server();
            	server.setSize(600, 480);
            	server.setTitle("Server");
            	server.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify                     
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    // End of variables declaration                   
}
